// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sales.Contexts;

#nullable disable

namespace Sales.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250109113203_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sales.Entities.DbModels.BuyerDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Sales.Entities.DbModels.ProductDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Sales.Entities.DbModels.SaleDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("SalesPointId")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SalesPointId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Sales.Entities.DbModels.SalesPointDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SalesPoints");
                });

            modelBuilder.Entity("Sales.Entities.DbModels.SaleDbModel", b =>
                {
                    b.HasOne("Sales.Entities.DbModels.BuyerDbModel", "BuyerDbModel")
                        .WithMany("SalesIds")
                        .HasForeignKey("BuyerId");

                    b.HasOne("Sales.Entities.DbModels.SalesPointDbModel", "SalesPointDbModel")
                        .WithMany("Sales")
                        .HasForeignKey("SalesPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Sales.Entities.DbModels.SaleDataDbModel", "SaleData", b1 =>
                        {
                            b1.Property<long>("SaleDbModelId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("ProductIdAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("ProductQuantity")
                                .HasColumnType("integer");

                            b1.HasKey("SaleDbModelId", "Id");

                            b1.ToTable("SalesData");

                            b1.WithOwner()
                                .HasForeignKey("SaleDbModelId");
                        });

                    b.Navigation("BuyerDbModel");

                    b.Navigation("SaleData");

                    b.Navigation("SalesPointDbModel");
                });

            modelBuilder.Entity("Sales.Entities.DbModels.SalesPointDbModel", b =>
                {
                    b.OwnsMany("Sales.Entities.DbModels.ProvidedProductDbModel", "ProvidedProducts", b1 =>
                        {
                            b1.Property<long>("SalesPointDbModelId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint");

                            b1.Property<int>("ProductQuantity")
                                .HasColumnType("integer");

                            b1.HasKey("SalesPointDbModelId", "Id");

                            b1.ToTable("ProvidedProducts");

                            b1.WithOwner()
                                .HasForeignKey("SalesPointDbModelId");
                        });

                    b.Navigation("ProvidedProducts");
                });

            modelBuilder.Entity("Sales.Entities.DbModels.BuyerDbModel", b =>
                {
                    b.Navigation("SalesIds");
                });

            modelBuilder.Entity("Sales.Entities.DbModels.SalesPointDbModel", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
